export interface KnowledgeCard {
  id: string
  title: string
  tags: string[]
  hook: string
  claims: string[]
  followups: string[]
}

export { GISUBIZO_PROMPTS, shufflePrompts } from './qa'

export const PHRASES: { rw: string; en: string }[] = [
  { rw: 'Muraho', en: 'hello (works all day)' },
  { rw: 'Bite se?', en: 'how are you?' },
  { rw: 'Ni meza', en: 'I am fine' },
  { rw: 'Murakoze', en: 'thank you' },
  { rw: 'Murakoze cyane', en: 'thank you very much' },
  { rw: 'Yego', en: 'yes' },
  { rw: 'Oya', en: 'no' },
  { rw: 'Amazi', en: 'water' },
  { rw: 'Mwiriwe', en: 'good afternoon / evening' },
  { rw: 'Mwaramutse', en: 'good morning' },
  { rw: 'Ijoro ryiza', en: 'good night' },
  { rw: 'Witwa nde?', en: 'what is your name?' },
  { rw: 'Nitwa…', en: 'my name is…' },
  { rw: 'Mwiriwe neza', en: 'a warm evening greeting' },
  { rw: 'Urakoze', en: 'thanks (to one person)' },
  { rw: 'Turongera', en: 'see you again' },
  { rw: 'Igisubizo', en: 'the answer' },
  { rw: 'Hamwe', en: 'together' },
  { rw: 'Amahoro', en: 'peace' },
  { rw: 'Nta kibazo', en: 'no problem' },
]

export const MONTHS: { id: string; rain: 'low' | 'mix' | 'high'; note: string }[] = [
  { id: 'january', rain: 'low', note: 'Warm dry-leaning days. Good for savannah and Kivu swimming. Gorilla trails are usually kinder than April.' },
  { id: 'february', rain: 'low', note: 'Still a dry-leaning window. Book permits now if you want June–August; those months fill first.' },
  { id: 'march', rain: 'high', note: 'Long rains begin. Forest is loud and green. Treks run; expect mud and fewer crowds.' },
  { id: 'april', rain: 'high', note: 'Kwibuka commemoration month. Heavy rain possible. Memorials are especially present. Pack a real shell.' },
  { id: 'may', rain: 'mix', note: 'Rains ease toward month’s end. Hills stay emerald. A smart shoulder if you have layers.' },
  { id: 'june', rain: 'low', note: 'Prime dry season. Cool mornings in the volcanoes. Highest demand for gorilla permits.' },
  { id: 'july', rain: 'low', note: 'Peak visitor month. Trails firmer, lodges busier. Book the circle early.' },
  { id: 'august', rain: 'low', note: 'Still dry and popular. Umuganura harvest energy in early August. Dust on eastern tracks.' },
  { id: 'september', rain: 'mix', note: 'Short rains can start late month. Still excellent. Slightly easier permits than July.' },
  { id: 'october', rain: 'high', note: 'Short rains. Nyungwe is theatrical. Bring gloves and a bag cover for cameras.' },
  { id: 'november', rain: 'high', note: 'Wet and quieter. Good for travellers who want forest over guaranteed blue sky.' },
  { id: 'december', rain: 'low', note: 'Second dry-leaning window. Festive Kigali, mild days, cold volcano dawns.' },
]

export const KNOWLEDGE: KnowledgeCard[] = [
  {
    id: 'country',
    title: 'Rwanda in one page',
    tags: ['rwanda', 'country', 'known', 'about', 'africa', 'hills', 'overview', 'facts', 'size', 'population'],
    hook: 'Rwanda is a compact East African country of a thousand hills — small enough to cross in a day, dense enough that volcanoes, rainforest, savannah, and an inland sea sit on one map.',
    claims: [
      'It is landlocked, bordered by Uganda, Tanzania, Burundi, and the Democratic Republic of the Congo.',
      'Kigali is the capital. Local time is CAT (UTC+2). The franc (RWF) is the currency.',
      'The official languages are Kinyarwanda, English, French, and Kiswahili. English is enough for Hamwe tours and Kigali visitor services.',
      'The country is 26,338 km², with a population of about 14 million.',
      'People come for mountain gorillas, a strikingly ordered capital, Nyungwe forest, Akagera’s lakes, and Lake Kivu’s slow western shore.',
      'Independence from Belgium was in 1962. The public story visitors meet first is recovery, cleanliness, and memory after 1994.',
      'Driving is on the right. Plastic bags are banned and taken at the airport.',
    ],
    followups: ['How do gorilla treks work?', 'When is the best time to visit?', 'What is Kigali like?'],
  },
  {
    id: 'kigali',
    title: 'Kigali',
    tags: ['kigali', 'capital', 'city', 'kisimenti', 'nyamirambo', 'airport', 'kgl', 'rebero', 'kimironko'],
    hook: 'Kigali is a hill city: clean, ordered, and built on ridges — the place you learn the country’s map before you leave it.',
    claims: [
      'You fly into Kigali International (KGL). Hamwe airport welcome is in a tour ticket.',
      'First days usually hold the Kigali Genocide Memorial, Nyamirambo food, Kimironko market, and a sunset from Rebero or Mount Kigali.',
      'Hamwe’s desk sits at Ikaze House, KG 11 Ave, Kisimenti. The city is walkable in pockets and safer than most regional capitals.',
      'Still keep bags close in markets, and use hotel taxis late at night.',
      'Inema Arts Centre, the Convocation view, and a long table in a courtyard are the usual second-day texture.',
      'Kigali sits near 1,500 m: mild days, cool nights, no coastal humidity.',
    ],
    followups: ['What should I do on day one?', 'Is Rwanda safe?', 'Where is the Hamwe office?'],
  },
  {
    id: 'dayone',
    title: 'Day one',
    tags: ['day', 'first', 'arrive', 'landing', 'jetlag', 'arrival'],
    hook: 'Day one in Rwanda should be a ridge, a meal, and an early night — not a gorilla attempt.',
    claims: [
      'Land, drop bags, walk a neighbourhood (Nyamirambo is the classic), and take a sunset so the hills sit in your body.',
      'Save the memorial for a morning with sleep in it, usually day two.',
      'Drink water, eat something familiar plus one Rwandan plate, and do not schedule a 04:30 volcano departure the same night you land.',
      'Hamwe’s Full Gathering and Kigali First Circle both start this way on purpose.',
    ],
    followups: ['How should I visit the memorial?', 'What is Kigali like?', 'How does a Hamwe circle work?'],
  },
  {
    id: 'gorillas',
    title: 'Mountain gorillas',
    tags: ['gorilla', 'gorillas', 'volcanoes', 'virunga', 'musanze', 'trek', 'permit', 'kinigi', 'sabyinyo', 'family'],
    hook: 'A gorilla morning is a scarce permit, a muddy climb in Volcanoes National Park, and one protected hour with a habituated family.',
    claims: [
      'Mountain gorillas live in the Virunga massif around Musanze / Kinigi, shared with Uganda and the DRC; Rwanda’s park is Volcanoes National Park.',
      'You walk with rangers to one family and stay one hour. You do not choose the family; weather and ranging decide the day.',
      'Fitness is moderate: steep, often muddy, anywhere from about 1 to 6 hours before the hour itself.',
      'The usual age minimum is 15. Children under that wait in Musanze.',
      'On Hamwe tours that list a trek, the permit is already in the fare — you do not hunt one at midnight on a third-party site.',
      'Rules at the family: stay 7–10 metres, no flash, masks if you have a cold, voices low, follow the ranger if a silverback advances.',
      'After the hour, keep the rest of the day quiet on purpose. Most people are more tired than they expected.',
      'Book early regardless of month. Dry months (June–September, December–February) mean less mud; green months mean fewer people.',
    ],
    followups: ['What should I pack for the trek?', 'Gorillas vs chimpanzees — what is the difference?', 'Which Hamwe tour includes gorillas?'],
  },
  {
    id: 'golden',
    title: 'Golden monkeys',
    tags: ['golden', 'monkey', 'monkeys', 'volcanoes', 'bamboo'],
    hook: 'Golden-monkey trekking is the lighter Virunga morning: bamboo, speed, and a different permit than gorillas.',
    claims: [
      'Golden monkeys live in the same Volcanoes National Park, often in bamboo on the lower slopes.',
      'The walk is usually shorter and less steep than a gorilla day, and the hour with the troop is the same idea: watch, do not chase.',
      'Photographers like them for colour and motion. They are not a substitute for gorillas; they are a second north-park chapter.',
      'Hamwe sometimes pairs them the day after gorillas when legs can still climb but the mind wants something brighter.',
    ],
    followups: ['How do gorilla treks work?', 'What should I pack?', 'Plan 5 days in Rwanda'],
  },
  {
    id: 'fossey',
    title: 'Dian Fossey and Bisoke',
    tags: ['fossey', 'dian', 'karisoke', 'bisoke', 'karisimbi', 'hike', 'grave'],
    hook: 'The Karisoke / Dian Fossey hike is a long uphill to a research story, not a gorilla viewing.',
    claims: [
      'Dian Fossey’s grave and the old Karisoke site sit high in Volcanoes National Park. The hike is its own permit and its own day.',
      'Mount Bisoke’s crater lake is a steep, often wet climb. Karisimbi is a serious overnight summit, not a casual add-on.',
      'Do not stack a gorilla trek and a Bisoke day back to back unless the circle is built for it.',
    ],
    followups: ['How do gorilla treks work?', 'What should I pack?', 'When is the best time to visit?'],
  },
  {
    id: 'nyungwe',
    title: 'Nyungwe',
    tags: ['nyungwe', 'canopy', 'chimpanzee', 'chimp', 'forest', 'tea', 'south', 'walkway'],
    hook: 'Nyungwe is Rwanda’s great south-west rainforest: chimpanzees, colobus, tea, and a hanging canopy walk in cool air.',
    claims: [
      'It is cooler, wetter, and earlier than people expect. Dawn starts are the point.',
      'Chimp trekking is a different permit and a different body of work than gorillas — faster animals, denser forest, less guarantee of a long sit.',
      'The canopy walkway is a hanging bridge in the trees, usually done as a guided hour, not a thrill ride.',
      'Hamwe treats Nyungwe as a forest chapter, not a day trip from Kigali. The tea-road in is part of the story.',
      'Colobus, birds, and orchids are the quiet reasons to linger a second night.',
    ],
    followups: ['What is the Nyungwe canopy walk like?', 'Gorillas vs chimpanzees — what is the difference?', 'Tell me about Lake Kivu'],
  },
  {
    id: 'canopy',
    title: 'Nyungwe canopy walk',
    tags: ['canopy', 'walkway', 'bridge', 'heights', 'afraid'],
    hook: 'The Nyungwe canopy walk is a guided hanging walkway above the forest floor — thrilling if you dislike heights, botanical if you do not.',
    claims: [
      'You cross with a ranger, clipped in, at a height that makes the canopy feel like a second ground.',
      'It is usually calmer than the photograph suggests. People with vertigo still do it; say so and walk slowly.',
      'Go early for clearer views and fewer groups. Mist is common and is not a failure of the day.',
      'Hamwe lists it as a together extra on some circles and inside Canopy & Kingdom.',
    ],
    followups: ['Tell me about Nyungwe', 'What should I pack?', 'How many days do I need?'],
  },
  {
    id: 'chimps',
    title: 'Chimpanzees',
    tags: ['chimp', 'chimps', 'chimpanzee', 'chimpanzees', 'nyungwe'],
    hook: 'Chimpanzee trekking in Nyungwe is a forest chase at first light, not the still hour you get with gorillas.',
    claims: [
      'You leave very early, listen for pant-hoots, and may walk hard before contact.',
      'Time with the group is limited and less portrait-like than gorillas. Success is high across a season, not guaranteed at 07:00 on your Tuesday.',
      'The permit is separate from the gorilla permit. Do not attempt both animals in one day.',
      'Gishwati-Mukura is a second, smaller forest option some travellers add; Nyungwe remains the main stage.',
    ],
    followups: ['Gorillas vs chimpanzees — what is the difference?', 'What is the Nyungwe canopy walk like?', 'When is the best time to visit?'],
  },
  {
    id: 'akagera',
    title: 'Akagera',
    tags: ['akagera', 'safari', 'big', 'five', 'elephant', 'lion', 'ihema', 'east', 'savannah', 'rhino', 'animals'],
    hook: 'Akagera is Rwanda’s eastern savannah: lakes, woodland, and a restored Big Five story on an intimate scale.',
    claims: [
      'Lions and rhinos were reintroduced in the last decade. Elephants, buffalo, leopard, giraffe, zebra, and plentiful antelope are the usual sightings.',
      'Game drives plus a boat on Lake Ihema are the classic pair. Hippos and birds steal the boat.',
      'It is not the Serengeti in scale. The surprise is light on the lakes and how quickly the hills fall away into acacia.',
      'Malaria precautions matter more here than in Kigali. Evenings can be warm; mornings are jacket weather on an open vehicle.',
      'Hamwe places Akagera after or before the volcanoes so the country has a wild east, not only a gorilla headline.',
    ],
    followups: ['Which animals live in Akagera?', 'How many days do I need?', 'Is Rwanda expensive?'],
  },
  {
    id: 'animals',
    title: 'Wildlife',
    tags: ['animals', 'wildlife', 'birds', 'lion', 'elephant', 'zebra', 'giraffe', 'hippo'],
    hook: 'Rwanda holds three wildlife ideas on one map: mountain gorillas, rainforest primates, and a recovering Big Five park.',
    claims: [
      'Volcanoes: mountain gorillas and golden monkeys.',
      'Nyungwe: chimpanzees, colobus, and a serious bird list.',
      'Akagera: lion, elephant, rhino, buffalo, leopard, giraffe, zebra, hippo, crocodile, and wetland birds on Ihema.',
      'Shoebill is a rare eastern-wetland prize, not a guarantee. Bring binoculars if birds are why you came.',
    ],
    followups: ['How do gorilla treks work?', 'Which animals live in Akagera?', 'Tell me about Nyungwe'],
  },
  {
    id: 'kivu',
    title: 'Lake Kivu',
    tags: ['kivu', 'lake', 'rubavu', 'gisenyi', 'kibuye', 'karongi', 'boat', 'coffee', 'west', 'swim'],
    hook: 'Lake Kivu is the inland sea on the Congo border — coffee, swimming, lamp boats, and the exhale after gorillas.',
    claims: [
      'Rubavu (once Gisenyi) is the livelier north shore; Karongi (Kibuye) is quieter islands and inlets.',
      'The water can look like a coast. Evenings drop; bring a light layer.',
      'Coffee cooperatives on the hills above the lake are one of the best half-days in the country.',
      'Hamwe uses Kivu as the pause between volcanoes and Nyungwe, or as its own six-day shore cohort.',
      'Swim where locals and lodges swim. The lake is famous, deep, and not a place to invent your own night crossing.',
    ],
    followups: ['What is there to eat?', 'When is the best time to visit?', 'How does a Hamwe circle work?'],
  },
  {
    id: 'when',
    title: 'When to visit',
    tags: ['when', 'weather', 'season', 'rain', 'dry', 'climate', 'best', 'month', 'june', 'april'],
    hook: 'Rwanda has two drier windows and two rainy ones — gorillas run all year; the choice is mud versus crowds.',
    claims: [
      'Drier: roughly June–September and December–February. Rainier: March–May and October–November.',
      'Kigali near 1,500 m stays mild. Volcanoes and Nyungwe are cold at dawn even in the dry months.',
      'There is no true winter and no closed gorilla season.',
      'April is also Kwibuka, the commemoration of the genocide — a month to visit memorials with extra care.',
      'Book gorilla permits first, then pick the month. July is easiest underfoot and hardest to book.',
    ],
    followups: ['What should I pack?', 'How do gorilla treks work?', 'Plan 5 days in Rwanda'],
  },
  {
    id: 'pack',
    title: 'What to pack',
    tags: ['pack', 'packing', 'clothes', 'boots', 'luggage', 'bring', 'wear', 'gloves', 'adapter'],
    hook: 'Pack for hills and forest, not a beach: layers, a rain shell, and shoes that have already been walked in.',
    claims: [
      'Broken-in trekking shoes, long sleeves for nettles, garden gloves for gorilla grab-stems, a buff, sunscreen, and a small daypack.',
      'Neutral colours in the parks. One smarter shirt for a Kigali long table.',
      'Adaptors are Type C / Type J, 230V.',
      'A reusable bottle — plastic bags are banned at the airport and you should not arrive with a stash of them.',
      'Cash in RWF for markets; cards in hotels. Binoculars if you care about birds. A dry bag for Nyungwe and April.',
      'For gorillas: rain trousers, a spare pair of socks, and no strong perfume.',
    ],
    followups: ['How do gorilla treks work?', 'What about money and francs?', 'Any cultural rules I should know?'],
  },
  {
    id: 'language',
    title: 'Kinyarwanda',
    tags: ['kinyarwanda', 'language', 'hello', 'words', 'muraho', 'murakoze', 'speak', 'phrase', 'english'],
    hook: 'A few Kinyarwanda words change the temperature of a stall; English already works in Kigali and on Hamwe days.',
    claims: [
      'Muraho is hello. Murakoze is thank you. Yego / Oya are yes / no. Amazi is water. Bite se? is how are you?',
      'Mwaramutse is good morning. Mwiriwe is good afternoon or evening. Ijoro ryiza is good night.',
      'Kinyarwanda, English, and French are official. Swahili helps in trade and on some buses.',
      'Hamwe hosts are bilingual. Practise “murakoze cyane” — it is the one phrase you will actually use ten times a day.',
    ],
    followups: ['Teach me a few Kinyarwanda words', 'What is Umuganda?', 'Any cultural rules I should know?'],
  },
  {
    id: 'money',
    title: 'Money and francs',
    tags: ['money', 'franc', 'rwf', 'currency', 'momo', 'payment', 'tip', 'atm', 'usd', 'expensive', 'cost', 'budget'],
    hook: 'Daily life runs on the Rwandan franc. Hamwe fares run from FRw 8,000 to FRw 80,000; luxury packages sit at that ceiling.',
    claims: [
      'ATMs in Kigali take Visa. MTN MoMo is how a lot of the country actually pays.',
      'Hamwe shows fares in FRw first. This demo locks FRw 1,450 = $1.',
      'USD is sometimes quoted for parks; you still want francs for markets, motos, and tips.',
      'Tip guides and drivers in cash when the day was real. Count your change without theatre.',
      'Budget traveler, excluding a hotel: transport FRw 8,000–10,000 a day, food FRw 5,000–10,000 a day, total FRw 10,000–20,000 a day.',
      'Comfortable traveler, excluding a hotel: transport FRw 10,000–25,000 a day, food FRw 10,000–20,000 a day, total FRw 20,000–45,000 a day.',
      'Using taxis or private cars frequently is often FRw 20,000–50,000 a day for transport alone.',
      'Hamwe day tickets are FRw 8,000–20,000. Circle tours are FRw 32,000–80,000. Luxury packages are FRw 80,000 — nothing on this site costs more.',
    ],
    followups: ['Can I pay with MoMo?', 'Is the gorilla permit included?', 'Is Rwanda expensive?'],
  },
  {
    id: 'visa',
    title: 'Visa and entry',
    tags: ['visa', 'entry', 'passport', 'yellow', 'fever', 'vaccine', 'evisa', 'irembo', 'immigration'],
    hook: 'Many passports enter Rwanda with a tourist visa on arrival or an e-visa — check Irembo for your nationality before you fly.',
    claims: [
      'A passport valid six months is the usual rule.',
      'Yellow-fever proof is asked if you arrive from an endemic country.',
      'Plastic bags are confiscated at KGL. Pack cubes, not shopping bags.',
      'Hamwe does not include the international flight. You fly to KGL; welcome is in the ticket.',
      'Rules change. The Directorate General of Immigration / Irembo list is the source, not a blog from 2019.',
    ],
    followups: ['Is Rwanda safe?', 'What should I pack?', 'Do I need malaria tablets?'],
  },
  {
    id: 'health',
    title: 'Health',
    tags: ['health', 'malaria', 'vaccine', 'altitude', 'doctor', 'tablets', 'yellow', 'pharmacy'],
    hook: 'Talk to a clinician before you fly: yellow fever if required, malaria especially for Akagera and the west, and a simple first-aid kit.',
    claims: [
      'Kigali’s altitude is mild. The volcanoes ask more of lungs and knees than of “altitude sickness” drama.',
      'There is no honest blanket “malaria-free Rwanda” claim. Risk is lower in the city, higher in the east and some western shores.',
      'Tap water in Kigali is treated; bottled or filtered on the road remains the usual habit.',
      'Pharmacies in Kigali are well stocked. Travel insurance that covers trekking is not optional if you are going into the park.',
      'If you have a cold, tell the gorilla ranger — respiratory illness is the reason for masks near the families.',
    ],
    followups: ['What should I pack?', 'Is Rwanda safe?', 'Which animals live in Akagera?'],
  },
  {
    id: 'safety',
    title: 'Safety',
    tags: ['safe', 'safety', 'crime', 'night', 'women', 'solo', 'lgbtq', 'travel'],
    hook: 'Rwanda is one of the more orderly countries in the region — that is a real advantage, not a spell.',
    claims: [
      'Visible community policing, a strong cleanliness ethic, and a capital that is walkable after dark in well-lit districts.',
      'Use hotel taxis at night, keep phones inward in crowds, and listen to your host on rural roads after rain.',
      'Solo travellers, including women, do this country constantly. Ordinary street sense still applies.',
      'The heavier thing is not street crime — it is arriving at memorials unprepared. Give those mornings space.',
      'Public life is conservative. Affection is quieter than in many European cities. Visitors are expected to dress modestly at memorials and churches.',
    ],
    followups: ['How should I visit the memorial?', 'What is Umuganda?', 'What should families know?'],
  },
  {
    id: 'memory',
    title: 'History and memorials',
    tags: ['genocide', 'memorial', '1994', 'history', 'kwibuka', 'tutsi', 'murambi', 'nyamata', 'ntarama'],
    hook: 'In 1994 the Genocide against the Tutsi killed about a million people in around 100 days. Visit as a witness, not as a stop between coffees.',
    claims: [
      'The Kigali Genocide Memorial is where most visitors begin — allow a quiet morning, no rushing into gorilla-chat afterwards.',
      'Nyamata, Ntarama, and Murambi are harder, more physical sites. Dress modestly. Do not photograph remains or interiors where it is forbidden.',
      'Kwibuka is the annual commemoration each April.',
      'Hamwe builds a memorial morning into Kigali days so the circle holds it together, not as a checkbox.',
      'Read a little before you go. Silence is a better offering than a performance of emotion.',
    ],
    followups: ['What is Kigali like?', 'What is Umuganda?', 'What should I do on day one?'],
  },
  {
    id: 'umuganda',
    title: 'Umuganda and public life',
    tags: ['umuganda', 'community', 'saturday', 'culture', 'rules', 'plastic', 'clean', 'etiquette'],
    hook: 'Umuganda is mandatory community work on the last Saturday morning of each month — the country pauses, and visitors respect the pause.',
    claims: [
      'Roads can be quieter; some businesses open late. Visitors are not usually conscripted.',
      'Plastic bags are banned. Public cleanliness is a civic project, not a tourist show.',
      'Point with the whole hand rather than one finger. Receive greetings or gifts with both hands or the right.',
      'Churches and memorials: shoulders covered. Hats off indoors.',
      'Greet people. A muraho at a stall is not decoration; it is how the exchange starts.',
    ],
    followups: ['Teach me a few Kinyarwanda words', 'Is Rwanda safe?', 'Any cultural rules I should know?'],
  },
  {
    id: 'food',
    title: 'Food and drink',
    tags: ['food', 'eat', 'coffee', 'tea', 'brochette', 'isombe', 'beer', 'akabenz', 'rolex', 'vegetarian'],
    hook: 'Rwandan tables run on brochettes, greens, beans, tilapia, and coffee that actually tastes of the hill it grew on.',
    claims: [
      'Isombe is cassava leaves. Ibitoke are plantains. Akabenz is pork. Ugali-style starches and beans show up everywhere.',
      'Rolex — chapati and egg — is a Kampala cousin that appears in Kigali nights.',
      'Primus and Virunga beers. Ikivuguto is fermented milk. Urwagwa is banana wine, more ceremony than bar drink.',
      'Rwanda grows excellent coffee and tea. A cooperative visit on Kivu is worth a morning.',
      'Tell Hamwe dietary rules on the circle call. Lodges can do vegetarian if they know. Vegan takes more planning outside Kigali.',
      'Tap water in the capital is treated; still, bottled or filtered on the road is the habit.',
    ],
    followups: ['What is there to do at night?', 'Tell me about Lake Kivu', 'How does a Hamwe circle work?'],
  },
  {
    id: 'night',
    title: 'Nights',
    tags: ['night', 'nightlife', 'jazz', 'bar', 'music', 'evening'],
    hook: 'Kigali nights are live music, courtyards, and an early last moto — not a 4 a.m. strip.',
    claims: [
      'Jazz rooms, hotel terraces, and Nyamirambo plates are the usual map.',
      'Hamwe’s long table and jazz-night extras exist because strangers eat better than they bar-hop.',
      'On trek days, sleep is the nightlife. Musanze and Nyungwe go dark on purpose.',
      'Kivu evenings are boats and a slower table. That is the country’s night face as much as the city.',
    ],
    followups: ['What is there to eat?', 'What is Kigali like?', 'How does a Hamwe circle work?'],
  },
  {
    id: 'arts',
    title: 'Arts and making',
    tags: ['imigongo', 'art', 'inema', 'basket', 'agaseke', 'intore', 'dance', 'craft'],
    hook: 'Imigongo spirals, agaseke baskets, and Intore dance are the country’s handmade memory — geometry, grass, and motion.',
    claims: [
      'Imigongo is traditional cow-dung and natural-pigment relief, black, cream, and oxblood. Hamwe runs a studio extra.',
      'Agaseke are the peace baskets you will see in markets. Buy from a cooperative if you can name one.',
      'Intore is the warrior dance still performed with real pride, not only for cameras.',
      'Inema and other Kigali studios are living contemporary rooms. Go after the memorial, not instead of it.',
      'Nyanza holds the King’s Palace and Inyambo cattle — the southern royal line, not a theme park.',
    ],
    followups: ['What is Imigongo?', 'Tell me about Nyanza', 'What should I do on day one?'],
  },
  {
    id: 'nyanza',
    title: 'Nyanza and the south',
    tags: ['nyanza', 'king', 'palace', 'inyambo', 'huye', 'butare', 'museum', 'kingdom'],
    hook: 'The south is kingdom roads: Nyanza’s palace and Inyambo cattle, Huye’s museum mind, then tea toward Nyungwe.',
    claims: [
      'The King’s Palace at Nyanza is the place to understand court life and the long-horned Inyambo.',
      'Huye (Butare) holds the national ethnographic museum — a slower, deeper afternoon than a market loop.',
      'Hamwe’s Canopy & Kingdom stitches this south with Nyungwe so forest and court share a week.',
    ],
    followups: ['Tell me about Nyungwe', 'What is Imigongo?', 'How many days do I need?'],
  },
  {
    id: 'transport',
    title: 'Getting around',
    tags: ['transport', 'moto', 'bus', 'taxi', 'car', 'drive', 'road', 'volcano', 'express'],
    hook: 'Without a car you move by moto-taxi in the city, coaches between towns, and a hosted vehicle if you joined a circle.',
    claims: [
      'Moto-taxis (with a helmet) are the Kigali default for short hills. Agree the fare or use a ride app where it works.',
      'Intercity coaches (Volcano, Trinity, and others) link Kigali to Musanze, Huye, Rubavu. Buy a seat, not a standing rumour.',
      'Roads are generally good. Rain still turns volcano tracks into work. Night rural driving is the main avoid.',
      'Driving is on the right. You do not need a car for a Hamwe circle — the vehicle is in the ticket.',
      'Domestic flights are rare and not how most people see this small country.',
    ],
    followups: ['How does a Hamwe circle work?', 'Is Rwanda safe?', 'How many days do I need?'],
  },
  {
    id: 'sim',
    title: 'Phones and internet',
    tags: ['sim', 'mtn', 'airtel', 'internet', 'wifi', 'phone', 'data'],
    hook: 'Buy an MTN or Airtel SIM at KGL or in town — data is cheap, coverage is serious, and MoMo lives on the same phone.',
    claims: [
      'Bring an unlocked phone. Passport is often asked at the SIM desk.',
      'Lodge wifi exists; Nyungwe and some Akagera corners still drop. Download maps offline.',
      'Hamwe hosts share a WhatsApp board on circles. You do not need roaming if you have a local SIM.',
    ],
    followups: ['Can I pay with MoMo?', 'What should I pack?', 'What about money and francs?'],
  },
  {
    id: 'family',
    title: 'Families and ages',
    tags: ['family', 'kids', 'children', 'child', 'age', 'teen', 'baby'],
    hook: 'Rwanda is kind to families in Kigali, Kivu, and Akagera. Gorilla day is not — the usual minimum age is 15.',
    claims: [
      'Under-15s do not join the gorilla trek. Design a Musanze morning for them, or wait.',
      'Golden monkeys and the canopy walk are often a better forest introduction for older children than chimps.',
      'Akagera game drives work for families who can sit still. Bring layers and snacks.',
      'Hamwe circles are adult-paced long tables. Write to the desk before you book a child onto a full gathering.',
    ],
    followups: ['How do gorilla treks work?', 'Plan 5 days in Rwanda', 'Is Rwanda safe?'],
  },
  {
    id: 'honeymoon',
    title: 'Slow trips and honeymoons',
    tags: ['honeymoon', 'couple', 'romantic', 'slow', 'private'],
    hook: 'The slow Rwanda is Kivu nights, a gorilla dawn, and fewer transfers — not twelve destinations in six days.',
    claims: [
      'A classic honeymoon sketch: two Kigali nights, three under the volcanoes, three on Kivu.',
      'Hamwe is a circle of strangers. Couples who want a private table should say so — or choose dates and lodges with the desk.',
      'Photography is generous. Build rest after the trek; the hour is emotional as well as physical.',
    ],
    followups: ['Tell me about Lake Kivu', 'How do gorilla treks work?', 'How many days do I need?'],
  },
  {
    id: 'photo',
    title: 'Photography',
    tags: ['photo', 'photography', 'camera', 'drone', 'flash', 'instagram'],
    hook: 'Bring a camera you can carry uphill. Leave the drone in the bag unless you have written park permission.',
    claims: [
      'No flash on gorillas or in memorial interiors. No photographing remains.',
      'Ask before portraits in markets. A muraho and a yes matter more than a long lens.',
      'Drones are tightly controlled. Parks and government buildings are not your backdrop by default.',
      'Rain covers and a spare battery matter more than a third lens. Nyungwe eats electronics that are not bagged.',
    ],
    followups: ['How should I visit the memorial?', 'How do gorilla treks work?', 'What should I pack?'],
  },
  {
    id: 'hamwe',
    title: 'How Hamwe works',
    tags: ['hamwe', 'circle', 'tour', 'ticket', 'host', 'seat', 'together', 'strangers', 'membership'],
    hook: 'Hamwe — “together” — sells dated seats on small hosted itineraries, not a buffet of options.',
    claims: [
      'You pick a departure, buy the ticket, meet the circle on a call two weeks out, then walk with a Kigali host.',
      'Circles are 10–14 people. Flights to KGL are yours. Lodges, park fees, and named meals are in the fare.',
      'When a gorilla trek is listed, the permit is included.',
      'Membership is extra: first look at seats and activity rates. It does not replace a tour ticket.',
      'The office is every day 08:00–18:00 CAT, lunch 12:00–13:30. Boarding a circle is separate from that clock.',
    ],
    followups: ['Which Hamwe tour includes gorillas?', 'Is the gorilla permit included?', 'When is the Kigali office open?'],
  },
  {
    id: 'hours',
    title: 'Hamwe desk hours',
    tags: ['hours', 'office', 'open', 'closed', 'desk', 'weekend', 'contact', 'phone', 'email', 'kisimenti', 'ikaze'],
    hook: 'The Kigali house at Ikaze House on KG 11 Ave, Kisimenti, keeps office hours every day.',
    claims: [
      'Every day, 08:00–18:00 CAT, with lunch 12:00–13:30.',
      'Write circle@hamwe.rw or +250 794 607 518.',
      'A tour can still have seats when the office is closed for the night. The radar on the site shows boarding, not the doorbell.',
    ],
    followups: ['How does a Hamwe circle work?', 'Can I pay with MoMo?', 'What is Kigali like?'],
  },
  {
    id: 'flights',
    title: 'Flights',
    tags: ['flight', 'flights', 'kgl', 'airline', 'airport', 'included'],
    hook: 'International flights are never in a Hamwe ticket. You fly into KGL; the circle starts at arrivals or the first Kigali table.',
    claims: [
      'Kigali is well connected via Nairobi, Addis, Istanbul, Brussels, Doha and other hubs. Schedules move — check the airline, not a screenshot.',
      'Airport welcome is included on hosted tours. Build a buffer before a gorilla dawn. Do not land at 22:00 and trek at 05:00.',
    ],
    followups: ['What should I do on day one?', 'How does a Hamwe circle work?', 'Do I need a visa?'],
  },
  {
    id: 'cancel',
    title: 'Changing a seat',
    tags: ['cancel', 'cancellation', 'refund', 'change', 'date'],
    hook: 'More than 30 days out, Hamwe can usually move you to another circle or refund minus permits already bought.',
    claims: [
      'Inside 30 days the seat is harder to refill — write to circle@hamwe.rw and expect the gorilla permit to be the sticky cost.',
      'Permits are named and dated. That is why last-minute gorilla changes are expensive everywhere, not only here.',
    ],
    followups: ['Is the gorilla permit included?', 'How does a Hamwe circle work?', 'When is the Kigali office open?'],
  },
  {
    id: 'days',
    title: 'How many days',
    tags: ['days', 'itinerary', 'week', 'duration', 'short', 'long', 'need', 'plan', 'schedule'],
    hook: 'Four days is a Kigali and gorilla dash. A week lets Kivu in. Twelve days is the country walked in order.',
    claims: [
      '2–3 days: Kigali only — memorial, markets, a hill sunset. Do not force gorillas.',
      '4–5 days: Kigali plus Volcanoes if the permit exists. Sleep in Musanze the night before.',
      '6–8 days: add Lake Kivu as the exhale. This is Hamwe’s Virunga Dawn / Kivu Shore territory.',
      '9–12 days: add Nyungwe or Akagera, or both on The Full Gathering.',
      'Transfers eat hours because the hills are real. A “see everything in five days” plan is a car, not a country.',
    ],
    followups: ['Plan 5 days in Rwanda', 'Which Hamwe tour includes gorillas?', 'What should I do on day one?'],
  },
]
