import type { Activity, AlbumPhoto, Destination, FaqItem, MembershipPlan, Tour, TravelerPreview } from './types'

export const BRAND = 'Hamwe'
export const TAGLINE = 'Arrive as strangers. Walk Rwanda as a circle.'

export const travelers: TravelerPreview[] = [
  {
    id: 't1',
    name: 'Amara Okonkwo',
    city: 'Lagos',
    country: 'Nigeria',
    role: 'guest',
    note: 'First gorilla trek. Wants a slow coffee morning.',
  },
  {
    id: 't2',
    name: 'Julian Hartmann',
    city: 'Berlin',
    country: 'Germany',
    role: 'guest',
    note: 'Birds, analog cameras, early starts.',
  },
  {
    id: 't3',
    name: 'Priya Menon',
    city: 'Bengaluru',
    country: 'India',
    role: 'guest',
    note: 'Here for Nyungwe and the canopy walk.',
  },
  {
    id: 't4',
    name: 'Noah Berg',
    city: 'Stockholm',
    country: 'Sweden',
    role: 'guest',
    note: 'Quiet hiker. Happy to share a tent story.',
  },
  {
    id: 't5',
    name: 'Aline Uwase',
    city: 'Kigali',
    country: 'Rwanda',
    role: 'host',
    note: 'Circle host. Keeps the days honest and the table full.',
  },
  {
    id: 't6',
    name: 'Mateo Silva',
    city: 'São Paulo',
    country: 'Brazil',
    role: 'guest',
    note: 'Came for Kivu. Staying for the people.',
  },
  {
    id: 't7',
    name: 'Hannah Cole',
    city: 'Toronto',
    country: 'Canada',
    role: 'guest',
    note: 'Memorial morning, market afternoon.',
  },
  {
    id: 't8',
    name: 'Kenji Watanabe',
    city: 'Osaka',
    country: 'Japan',
    role: 'guest',
    note: 'Tea fields and night sounds.',
  },
  {
    id: 't9',
    name: 'Sara Al-Farsi',
    city: 'Muscat',
    country: 'Oman',
    role: 'guest',
    note: 'Joining the circle with her sister.',
  },
  {
    id: 't10',
    name: 'David Nkrumah',
    city: 'Accra',
    country: 'Ghana',
    role: 'guest',
    note: 'Wants the full gathering, not a checklist.',
  },
]

export const tours: Tour[] = [
  {
    id: 'tour-gathering',
    slug: 'full-rwanda-gathering',
    name: 'The Full Gathering',
    tagline: 'Twelve days. One small circle. The country, walked in order.',
    durationDays: 12,
    startCity: 'Kigali',
    endCity: 'Kigali',
    nextDeparture: '2026-10-14',
    priceUsd: 4280,
    seatsTotal: 14,
    seatsTaken: 9,
    difficulty: 'moderate',
    region: 'Countrywide',
    cohortName: 'October Circle',
    image: '/images/cohort.png',
    gallery: ['/images/kigali.png', '/images/gorilla-volcanoes.png', '/images/lake-kivu.png', '/images/nyungwe.png'],
    highlights: [
      'Gorilla trek in Volcanoes National Park',
      'Lake Kivu nights and coffee cooperatives',
      'Nyungwe canopy + chimpanzee morning',
      'Akagera game drive and Lake Ihema',
      'Kigali memorial, markets, and farewell table',
    ],
    includes: [
      'All lodges and park fees, including gorilla permit',
      'Private circle vehicle and bilingual host',
      'Breakfasts, most lunches, four communal dinners',
      'Pre-departure circle call two weeks before',
      'Airport welcome in Kigali',
    ],
    itinerary: [
      {
        day: 1,
        title: 'The hill city',
        location: 'Kigali',
        summary:
          'Land, drop bags, walk Nyamirambo with a local guide. Sunset from Rebero so the map of hills sits in your body before the itinerary does.',
        meals: 'Dinner',
      },
      {
        day: 2,
        title: 'Memory, then making',
        location: 'Kigali',
        summary:
          'Morning at the Kigali Genocide Memorial. Afternoon at Inema Arts and Kimironko market. The circle eats together and learns each other’s names for real.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 3,
        title: 'North to the volcanoes',
        location: 'Musanze',
        summary:
          'Drive the thousand hills to Musanze. Twin lakes walk. Briefing for the gorilla day. Early night.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 4,
        title: 'Among the gorillas',
        location: 'Volcanoes National Park',
        summary:
          'Pre-dawn departure. One hour with a mountain gorilla family. The rest of the day is quiet on purpose.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 5,
        title: 'Culture on the lava',
        location: 'Iby’Iwacu · Musanze',
        summary:
          'Golden monkeys or a Dian Fossey hike, then Iby’Iwacu cultural village. Stories, dance, and a home lunch.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 6,
        title: 'The inland sea',
        location: 'Rubavu, Lake Kivu',
        summary:
          'West to Kivu. Swim, walk the lakeside, watch the fishermen’s lamps come on.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 7,
        title: 'Coffee and still water',
        location: 'Lake Kivu',
        summary:
          'Cooperative visit from cherry to cup. Free afternoon. Optional kayak. Circle dinner on the terrace.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 8,
        title: 'South through tea',
        location: 'Nyungwe',
        summary:
          'Long beautiful drive through tea plantations into the rainforest. Lodge fire. Night sounds.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 9,
        title: 'Canopy and chimps',
        location: 'Nyungwe National Park',
        summary:
          'Canopy walkway at first light. Chimpanzee tracking or a waterfall hike. The forest does the talking.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 10,
        title: 'Kingdom roads',
        location: 'Huye · Nyanza',
        summary:
          'Ethnographic Museum in Huye, then the King’s Palace in Nyanza with the long-horned Inyambo cattle.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 11,
        title: 'East to the wild',
        location: 'Akagera National Park',
        summary:
          'Game drive through savannah and lakes. Boat on Lake Ihema at dusk if the light holds.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 12,
        title: 'Return and table',
        location: 'Kigali',
        summary:
          'Back to Kigali. Farewell lunch. Airport transfers as needed. You leave with names, not just photographs.',
        meals: 'Breakfast, lunch',
      },
    ],
  },
  {
    id: 'tour-virunga',
    slug: 'virunga-dawn-circle',
    name: 'Virunga Dawn Circle',
    tagline: 'Eight days under the volcanoes, built around one unforgettable hour.',
    durationDays: 8,
    startCity: 'Kigali',
    endCity: 'Kigali',
    nextDeparture: '2026-11-02',
    priceUsd: 3120,
    seatsTotal: 12,
    seatsTaken: 8,
    difficulty: 'active',
    region: 'North',
    cohortName: 'November Mist',
    image: '/images/gorilla-volcanoes.png',
    gallery: ['/images/gorilla-volcanoes.png', '/images/hero-hills.png', '/images/kigali.png'],
    highlights: [
      'Gorilla permit and trek included',
      'Twin lakes and Musanze caves',
      'Iby’Iwacu community visit',
      'Two nights to arrive, not rush',
    ],
    includes: [
      'Gorilla permit and park fees',
      '7 nights lodge',
      'Circle host and driver',
      'Most meals',
      'Pre-trip circle introduction',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Kigali landing',
        location: 'Kigali',
        summary: 'Airport pickup, city orientation, welcome dinner on a hill terrace.',
        meals: 'Dinner',
      },
      {
        day: 2,
        title: 'The capital properly',
        location: 'Kigali',
        summary: 'Memorial, crafts, and a long lunch. Drive north after siesta hour.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 3,
        title: 'Lakes under volcanoes',
        location: 'Burera & Ruhondo',
        summary: 'Walk the twin lakes. Briefing. Early sleep.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 4,
        title: 'Gorilla day',
        location: 'Volcanoes National Park',
        summary: 'The trek. Silence after. Hot lunch back at the lodge.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 5,
        title: 'Second mountain',
        location: 'Volcanoes National Park',
        summary: 'Golden monkeys or a crater hike. Those who want rest, rest.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 6,
        title: 'Village day',
        location: 'Kinigi',
        summary: 'Iby’Iwacu. Dance, archery, and a shared meal with the community.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 7,
        title: 'Return south',
        location: 'Kigali',
        summary: 'Scenic drive, last-night table, optional night market.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 8,
        title: 'Departures',
        location: 'Kigali',
        summary: 'Breakfast, transfers, and a WhatsApp circle that usually stays alive.',
        meals: 'Breakfast',
      },
    ],
  },
  {
    id: 'tour-kivu',
    slug: 'kivu-shore-cohort',
    name: 'Kivu Shore Cohort',
    tagline: 'Six unhurried days on the inland sea — swim, coffee, strangers at one table.',
    durationDays: 6,
    startCity: 'Kigali',
    endCity: 'Kigali',
    nextDeparture: '2026-10-22',
    priceUsd: 1680,
    seatsTotal: 12,
    seatsTaken: 5,
    difficulty: 'gentle',
    region: 'West',
    cohortName: 'Shore Table',
    image: '/images/lake-kivu.png',
    gallery: ['/images/lake-kivu.png', '/images/coffee.png', '/images/dinner.png'],
    highlights: [
      'Three nights on Lake Kivu',
      'Coffee cooperative from cherry to cup',
      'Sunset boat with the circle',
      'Kigali bookends',
    ],
    includes: [
      'Lodges and Kivu boat',
      'Coffee visit',
      'Host and transport',
      'Breakfasts and three dinners',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Meet in Kigali',
        location: 'Kigali',
        summary: 'Names, a city walk, first dinner. No rushing to the lake on day one.',
        meals: 'Dinner',
      },
      {
        day: 2,
        title: 'Westward',
        location: 'Rubavu',
        summary: 'Drive to Kivu. Swim. Terrace sundowners.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 3,
        title: 'Coffee hills',
        location: 'Lake Kivu',
        summary: 'Cooperative visit, optional kayak, long lunch.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 4,
        title: 'Boat day',
        location: 'Lake Kivu',
        summary: 'Circle boat along the shore. Picnic islands. Night market if you want it.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 5,
        title: 'Back to the capital',
        location: 'Kigali',
        summary: 'Scenic return. Farewell dinner in a courtyard.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 6,
        title: 'Soft landing',
        location: 'Kigali',
        summary: 'Breakfast and airport runs. Keep the circle chat.',
        meals: 'Breakfast',
      },
    ],
  },
  {
    id: 'tour-canopy',
    slug: 'canopy-and-kingdom',
    name: 'Canopy & Kingdom',
    tagline: 'Rainforest, tea, and the old royal roads of the south.',
    durationDays: 9,
    startCity: 'Kigali',
    endCity: 'Kigali',
    nextDeparture: '2026-11-18',
    priceUsd: 2460,
    seatsTotal: 12,
    seatsTaken: 4,
    difficulty: 'moderate',
    region: 'South & West',
    cohortName: 'Tea Line',
    image: '/images/nyungwe.png',
    gallery: ['/images/nyungwe.png', '/images/imigongo.png', '/images/hero-hills.png'],
    highlights: [
      'Nyungwe canopy walk',
      'Chimpanzee tracking',
      'King’s Palace and Inyambo cattle',
      'Imigongo studio in the east-south corridor',
    ],
    includes: [
      'Park fees and canopy walk',
      'Museum and palace entries',
      'Lodges, host, vehicle',
      'Most meals',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Gather',
        location: 'Kigali',
        summary: 'Welcome walk and dinner.',
        meals: 'Dinner',
      },
      {
        day: 2,
        title: 'South',
        location: 'Huye',
        summary: 'Ethnographic Museum. Overnight in the university town.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 3,
        title: 'Palace',
        location: 'Nyanza',
        summary: 'King’s Palace, Inyambo cattle, then onward toward the forest.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 4,
        title: 'Tea line',
        location: 'Nyungwe',
        summary: 'Plantation walk and lodge arrival.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 5,
        title: 'Canopy',
        location: 'Nyungwe National Park',
        summary: 'Walkway at first light. Waterfall afternoon.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 6,
        title: 'Chimpanzees',
        location: 'Nyungwe National Park',
        summary: 'Tracking morning. Slow afternoon.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 7,
        title: 'Pattern and pigment',
        location: 'East-south studios',
        summary: 'Imigongo workshop with a master artist. You take a panel home.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 8,
        title: 'Kigali night',
        location: 'Kigali',
        summary: 'Return, last dinner, optional jazz.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 9,
        title: 'Depart',
        location: 'Kigali',
        summary: 'Transfers.',
        meals: 'Breakfast',
      },
    ],
  },
  {
    id: 'tour-akagera',
    slug: 'akagera-wild-circle',
    name: 'Akagera Wild Circle',
    tagline: 'Five days of savannah, lakes, and a boat at the edge of the day.',
    durationDays: 5,
    startCity: 'Kigali',
    endCity: 'Kigali',
    nextDeparture: '2026-10-29',
    priceUsd: 1540,
    seatsTotal: 10,
    seatsTaken: 6,
    difficulty: 'gentle',
    region: 'East',
    cohortName: 'Ihema Light',
    image: '/images/akagera.png',
    gallery: ['/images/akagera.png', '/images/hero-hills.png', '/images/dinner.png'],
    highlights: [
      'Two game drives in Akagera',
      'Boat on Lake Ihema',
      'Night in a park-edge lodge',
      'Small circle of ten',
    ],
    includes: [
      'Park fees and boat',
      'Lodge nights',
      'Guide and vehicle',
      'All meals in park',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Meet and brief',
        location: 'Kigali',
        summary: 'Circle dinner and safari briefing.',
        meals: 'Dinner',
      },
      {
        day: 2,
        title: 'Into the park',
        location: 'Akagera',
        summary: 'Drive east. Afternoon game drive.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 3,
        title: 'Full wild day',
        location: 'Akagera',
        summary: 'Dawn drive, rest, dusk boat on Ihema.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 4,
        title: 'Last light',
        location: 'Akagera · Kigali',
        summary: 'Morning game drive, return to Kigali, courtyard dinner.',
        meals: 'Breakfast, lunch, dinner',
      },
      {
        day: 5,
        title: 'Out',
        location: 'Kigali',
        summary: 'Breakfast and airport.',
        meals: 'Breakfast',
      },
    ],
  },
  {
    id: 'tour-kigali',
    slug: 'kigali-first-circle',
    name: 'Kigali First Circle',
    tagline: 'Four days to learn the capital with people, not a checklist.',
    durationDays: 4,
    startCity: 'Kigali',
    endCity: 'Kigali',
    nextDeparture: '2026-10-17',
    priceUsd: 640,
    seatsTotal: 14,
    seatsTaken: 11,
    difficulty: 'gentle',
    region: 'Kigali',
    cohortName: 'Hill Weekend',
    image: '/images/kigali.png',
    gallery: ['/images/kigali.png', '/images/imigongo.png', '/images/dinner.png'],
    highlights: [
      'Memorial and city hills',
      'Nyamirambo food walk',
      'Inema and Kimironko',
      'One long communal table',
    ],
    includes: [
      '3 nights boutique stay',
      'All listed visits',
      'Circle host',
      'Breakfasts and two dinners',
    ],
    itinerary: [
      {
        day: 1,
        title: 'Arrive on a hill',
        location: 'Kigali',
        summary: 'Check-in, orientation walk, dinner.',
        meals: 'Dinner',
      },
      {
        day: 2,
        title: 'Memory and market',
        location: 'Kigali',
        summary: 'Memorial morning. Kimironko afternoon.',
        meals: 'Breakfast, lunch',
      },
      {
        day: 3,
        title: 'Making and Nyamirambo',
        location: 'Kigali',
        summary: 'Inema studio, fabric, and a Nyamirambo food walk after dark.',
        meals: 'Breakfast, dinner',
      },
      {
        day: 4,
        title: 'Last coffee',
        location: 'Kigali',
        summary: 'Slow breakfast. Transfers.',
        meals: 'Breakfast',
      },
    ],
  },
]

export const activities: Activity[] = [
  {
    id: 'act-imigongo',
    slug: 'imigongo-studio',
    name: 'Imigongo studio',
    city: 'Kigali / East',
    duration: '3 hours',
    priceUsd: 55,
    nextSlot: '2026-10-16',
    spotsLeft: 6,
    spotsTotal: 10,
    category: 'culture',
    image: '/images/imigongo.png',
    description:
      'Learn the geometry of Imigongo — black, cream, and oxblood spirals — from a working studio. You leave with a small panel and red under your nails.',
    togetherNote: 'Pairs well with any Kigali night. Strangers share a workbench.',
    includes: ['Materials', 'Studio fee', 'Tea'],
  },
  {
    id: 'act-coffee',
    slug: 'cherry-to-cup',
    name: 'Cherry to cup',
    city: 'Lake Kivu',
    duration: '4 hours',
    priceUsd: 48,
    nextSlot: '2026-10-23',
    spotsLeft: 8,
    spotsTotal: 12,
    category: 'food',
    image: '/images/coffee.png',
    description:
      'Walk a cooperative from red cherry to washed parchment to the cupping table. Farmers host. The circle tastes blind and argues kindly.',
    togetherNote: 'Best as a Kivu Shore extra. Open to any Hamwe traveler in town.',
    includes: ['Cooperative visit', 'Tasting flight', 'Light lunch'],
  },
  {
    id: 'act-dinner',
    slug: 'long-table-kigali',
    name: 'Long table, Kigali',
    city: 'Kigali',
    duration: '3.5 hours',
    priceUsd: 42,
    nextSlot: '2026-10-15',
    spotsLeft: 4,
    spotsTotal: 14,
    category: 'food',
    image: '/images/dinner.png',
    description:
      'A courtyard supper for people who arrived alone. Isombe, brochettes, akabenz, sorghum juice. Place cards mix the table on purpose.',
    togetherNote: 'The original Hamwe ritual. Come even if you are not on a full tour.',
    includes: ['Shared menu', 'Welcome drink', 'Host'],
  },
  {
    id: 'act-canopy',
    slug: 'canopy-add-on',
    name: 'Nyungwe canopy hour',
    city: 'Nyungwe',
    duration: '2 hours',
    priceUsd: 70,
    nextSlot: '2026-11-20',
    spotsLeft: 9,
    spotsTotal: 12,
    category: 'nature',
    image: '/images/nyungwe.png',
    description:
      'A first-light walk on the hanging bridge if your tour does not already include it — or a second pass for people who want the mist twice.',
    togetherNote: 'Small group. Guides wait for the slowest camera.',
    includes: ['Park entry add-on', 'Guide'],
  },
  {
    id: 'act-boat',
    slug: 'kivu-lamp-boat',
    name: 'Kivu lamp boat',
    city: 'Rubavu',
    duration: '2 hours',
    priceUsd: 38,
    nextSlot: '2026-10-24',
    spotsLeft: 7,
    spotsTotal: 10,
    category: 'night',
    image: '/images/lake-kivu.png',
    description:
      'Evening boat as the fishing lamps come on. The circle sits on the same bench and watches the water turn copper.',
    togetherNote: 'Open seats for any traveler on the shore that night.',
    includes: ['Boat', 'Captain', 'Blanket'],
  },
  {
    id: 'act-hills',
    slug: 'twin-lakes-walk',
    name: 'Twin lakes walk',
    city: 'Musanze',
    duration: '5 hours',
    priceUsd: 36,
    nextSlot: '2026-11-03',
    spotsLeft: 10,
    spotsTotal: 12,
    category: 'nature',
    image: '/images/hero-hills.png',
    description:
      'A guided walk between Lakes Burera and Ruhondo. Terraces, children selling passion fruit, volcanoes on the skyline.',
    togetherNote: 'Easy miles. Good for people who want to talk while they walk.',
    includes: ['Guide', 'Fruit stop'],
    meetingPoint: 'Kinigi visitor centre, Musanze',
  },
  {
    id: 'act-memorial',
    slug: 'memorial-morning',
    name: 'Memorial morning',
    city: 'Kigali',
    duration: '3 hours',
    priceUsd: 28,
    nextSlot: '2026-10-16',
    spotsLeft: 8,
    spotsTotal: 12,
    category: 'culture',
    image: '/images/kigali.png',
    description:
      'A guided morning at the Kigali Genocide Memorial with time after to sit, not rush. The circle stays small so the hour can stay quiet.',
    togetherNote: 'Open to Hamwe travelers and to people in Kigali who want company, not a crowd.',
    includes: ['Entry', 'Guide', 'Quiet hour after'],
    meetingPoint: 'Kigali Genocide Memorial, Gisozi',
  },
  {
    id: 'act-market',
    slug: 'kimironko-market-walk',
    name: 'Kimironko market walk',
    city: 'Kigali',
    duration: '2.5 hours',
    priceUsd: 32,
    nextSlot: '2026-10-18',
    spotsLeft: 9,
    spotsTotal: 12,
    category: 'food',
    image: '/images/kigali.png',
    description:
      'Fruit, fabric, brochettes, and the noise of a working capital. A host who shops there walks you through without turning it into a photoshoot.',
    togetherNote: 'Best the afternoon you land, before the hills start.',
    includes: ['Host', 'Tasting stops'],
    meetingPoint: 'Kimironko market gate',
  },
  {
    id: 'act-caves',
    slug: 'musanze-caves',
    name: 'Musanze caves',
    city: 'Musanze',
    duration: '2 hours',
    priceUsd: 40,
    nextSlot: '2026-11-04',
    spotsLeft: 7,
    spotsTotal: 10,
    category: 'nature',
    image: '/images/gorilla-volcanoes.png',
    description:
      'Lava tunnels under the volcanoes, helmets on, lamps low. A short walk that still feels like another country under the country.',
    togetherNote: 'Pairs with Virunga Dawn. Bring a jacket.',
    includes: ['Entry', 'Lamp and helmet', 'Guide'],
    meetingPoint: 'Musanze caves ticket office',
  },
  {
    id: 'act-jazz',
    slug: 'kigali-jazz-night',
    name: 'Kigali jazz night',
    city: 'Kigali',
    duration: '3 hours',
    priceUsd: 34,
    nextSlot: '2026-10-19',
    spotsLeft: 6,
    spotsTotal: 14,
    category: 'night',
    image: '/images/dinner.png',
    description:
      'A reserved table for the circle at a hill jazz room. One drink included. The rest is conversation and whatever the band decides.',
    togetherNote: 'Come even if you travelled alone. Place cards mix the table.',
    includes: ['Seat', 'Welcome drink', 'Host'],
    meetingPoint: 'The Jazz Club, Kiyovu',
  },
]

export const destinations: Destination[] = [
  {
    id: 'd-kigali',
    slug: 'kigali',
    name: 'Kigali',
    region: 'Capital hills',
    blurb: 'Memorial mornings, Nyamirambo food, a city that teaches the map of hills before the itinerary does.',
    image: '/images/kigali.png',
    tourSlug: 'kigali-first-circle',
  },
  {
    id: 'd-volcanoes',
    slug: 'volcanoes',
    name: 'Volcanoes',
    region: 'North · Musanze',
    blurb: 'One hour with a gorilla family. The rest of the day is quiet on purpose.',
    image: '/images/gorilla-volcanoes.png',
    tourSlug: 'virunga-dawn-circle',
  },
  {
    id: 'd-kivu',
    slug: 'kivu',
    name: 'Lake Kivu',
    region: 'West · Rubavu',
    blurb: 'Coffee cooperatives, lamp boats, and a table that stays late on the inland sea.',
    image: '/images/lake-kivu.png',
    tourSlug: 'kivu-shore-cohort',
  },
  {
    id: 'd-nyungwe',
    slug: 'nyungwe',
    name: 'Nyungwe',
    region: 'South-west forest',
    blurb: 'Canopy walkway at first light. Chimpanzees. Tea on the way in.',
    image: '/images/nyungwe.png',
    tourSlug: 'canopy-and-kingdom',
  },
  {
    id: 'd-akagera',
    slug: 'akagera',
    name: 'Akagera',
    region: 'East savannah',
    blurb: 'Game drives, lakes, and a boat on Ihema when the light holds.',
    image: '/images/akagera.png',
    tourSlug: 'akagera-wild-circle',
  },
  {
    id: 'd-nyanza',
    slug: 'nyanza',
    name: 'Nyanza',
    region: 'Kingdom roads',
    blurb: 'The King’s Palace, Inyambo cattle, and the old royal line of the south.',
    image: '/images/imigongo.png',
    tourSlug: 'canopy-and-kingdom',
  },
]

export const memberships: MembershipPlan[] = [
  {
    id: 'mem-month',
    slug: 'circle-month',
    name: 'Circle month',
    period: 'month',
    priceUsd: 32,
    tagline: 'One month of first look at seats, activity rates, and the host table in Kigali.',
    perks: ['Activity seats at member fare', 'WhatsApp circle board', 'One long-table supper'],
  },
  {
    id: 'mem-year',
    slug: 'circle-year',
    name: 'Circle year',
    period: 'year',
    priceUsd: 290,
    tagline: 'A year of Hamwe. Tours still cost a ticket. The extras and the first seats are yours.',
    perks: [
      'Early boarding on every departure',
      '15% off together extras',
      'Four hosted Kigali tables',
      'Airport welcome even when you are not on a tour',
    ],
    highlighted: true,
  },
  {
    id: 'mem-host',
    slug: 'host-table',
    name: 'Host table',
    period: 'year',
    priceUsd: 468,
    tagline: 'For people who return. A year of the circle plus a named seat at every Kigali supper.',
    perks: ['Everything in Circle year', 'Named supper seat', 'A host call before each trip', 'Guest pass for one friend, once'],
  },
]

export const faqs: FaqItem[] = [
  {
    q: 'Do I pay in Rwandan francs?',
    a: 'Yes. Fares are shown in FRw first, with a locked USD line underneath (FRw 1,450 = $1 on this demo). MoMo and QR settle in RWF. Cards and PayPal can still pay the same franc total.',
  },
  {
    q: 'Is the gorilla permit included?',
    a: 'When a trek is listed on the tour, the permit is already in the fare. You do not buy it at midnight on a third-party site.',
  },
  {
    q: 'Can I pay with MTN MoMo?',
    a: 'Yes. Choose MoMo at checkout, enter a Rwanda number (07…), and approve the prompt on the phone. This build is a demo — no live debit until a merchant account is connected.',
  },
  {
    q: 'How do Apple Wallet and Calendar work?',
    a: 'After payment you get a QR boarding pass. Add to Calendar downloads an .ics file iPhone Calendar understands. Add to Apple Wallet downloads a pass file — a signed .pkpass needs Apple certificates in production.',
  },
  {
    q: 'What is a Circle membership?',
    a: 'A subscription on top of tickets, not instead of them. Members see seats first and pay less on activities. Gorilla days and lodges remain one-off fares.',
  },
  {
    q: 'Are flights to Kigali included?',
    a: 'No. You fly to KGL. Airport welcome, the vehicle, lodges, and named meals are in the ticket.',
  },
  {
    q: 'Can I cancel?',
    a: 'More than 30 days out, we move you to another circle or refund minus permit costs already bought. Inside 30 days, the seat is harder to refill — write to circle@hamwe.rw.',
  },
  {
    q: 'Who is this for?',
    a: 'Adults who will sit at a long table and walk at the group’s pace. You do not need to know anyone when you buy the seat.',
  },
  {
    q: 'When is the Kigali office open?',
    a: 'Monday to Friday, 08:00–18:00 CAT. The desk is closed Saturday and Sunday. Circle boarding still shows as open or closed on the radar whenever seats remain.',
  },
]

export const letters = [
  {
    name: 'Priya M.',
    tour: 'Canopy & Kingdom',
    text: 'I booked a ticket because I did not want to invent a trip. I left with eight people I still write to. Rwanda did the landscape. Hamwe did the table.',
  },
  {
    name: 'Julian H.',
    tour: 'Virunga Dawn',
    text: 'The gorilla hour is what you think. The surprise was breakfast the next day — twelve quiet people who had seen the same thing and did not need to perform it.',
  },
  {
    name: 'Amara O.',
    tour: 'The Full Gathering',
    text: 'I was nervous about strangers. The circle call before we flew took that apart. By Kivu I had people I would miss.',
  },
]

export const album: AlbumPhoto[] = [
  {
    id: 'hills',
    src: '/images/hero-hills.png',
    title: 'Thousand hills',
    place: 'Rural terraces',
    caption: 'The map of Rwanda is a staircase of green. Morning mist sits in the folds.',
  },
  {
    id: 'gorillas',
    src: '/images/gorilla-volcanoes.png',
    title: 'Among the gorillas',
    place: 'Volcanoes National Park',
    caption: 'One hour with a family in the bamboo. The rest of the day is quiet on purpose.',
  },
  {
    id: 'kivu',
    src: '/images/lake-kivu.png',
    title: 'Inland sea',
    place: 'Lake Kivu · Rubavu',
    caption: 'Lamp boats, coffee cooperatives, and a table that stays late on the water.',
  },
  {
    id: 'nyungwe',
    src: '/images/nyungwe.png',
    title: 'Canopy hour',
    place: 'Nyungwe Forest',
    caption: 'A hanging bridge at first light. Chimpanzees somewhere in the same trees.',
  },
  {
    id: 'akagera',
    src: '/images/akagera.png',
    title: 'East savannah',
    place: 'Akagera National Park',
    caption: 'Game drives, lakes, and a boat on Ihema when the light holds.',
  },
  {
    id: 'kigali',
    src: '/images/kigali.png',
    title: 'Hill city',
    place: 'Kigali',
    caption: 'Nyamirambo food, memorial mornings, a city that teaches the hills before the itinerary does.',
  },
  {
    id: 'cohort',
    src: '/images/cohort.png',
    title: 'The circle walking',
    place: 'On the road',
    caption: 'Ten to fourteen people. A host from Kigali. The country in a sensible order.',
  },
  {
    id: 'coffee',
    src: '/images/coffee.png',
    title: 'Cherry and wash',
    place: 'Western cooperatives',
    caption: 'Hands in the cherries. The smell of washed arabica before the lake.',
  },
  {
    id: 'table',
    src: '/images/dinner.png',
    title: 'Long table',
    place: 'Kigali · Kivu',
    caption: 'This is the product: strangers who become a table.',
  },
  {
    id: 'imigongo',
    src: '/images/imigongo.png',
    title: 'Imigongo',
    place: 'Studio geometry',
    caption: 'Cow-dung painting, black and white and gold — Rwanda’s own line work.',
  },
  {
    id: 'nyanza',
    src: '/images/nyanza.png',
    title: 'Kingdom roads',
    place: 'Nyanza',
    caption: 'The King’s Palace, Inyambo cattle, and the old royal line of the south.',
  },
  {
    id: 'atlas',
    src: '/images/atlas-rwanda.png',
    title: 'The country as a map',
    place: 'Rwanda',
    caption: 'North volcanoes, west water, south forest, east game, a capital of hills.',
  },
  {
    id: 'kigali-dusk',
    src: '/images/album/kigali-dusk.jpg',
    title: 'Kigali at dusk',
    place: 'Kigali',
    caption: 'The convention crown and the hills going gold. The desk sits in this city.',
  },
  {
    id: 'nyamirambo',
    src: '/images/album/nyamirambo.jpg',
    title: 'Mount Kigali sunset',
    place: 'Kigali',
    caption: 'The capital from the hill. This is the light after a memorial morning.',
  },
  {
    id: 'rebero',
    src: '/images/album/rebero-sunset.jpg',
    title: 'Rebero light',
    place: 'Kigali',
    caption: 'Sunset from the viewpoint so the map of hills sits in your body.',
  },
  {
    id: 'sabyinyo',
    src: '/images/album/sabyinyo.jpg',
    title: 'Sabyinyo',
    place: 'Volcanoes National Park',
    caption: 'The old teeth of the Virungas. Gorilla briefing is the night before.',
  },
  {
    id: 'kivu-shore',
    src: '/images/album/kivu-shore.jpg',
    title: 'Kivu shore',
    place: 'Lake Kivu',
    caption: 'An inland sea between Rwanda and Congo. The circle sleeps by the water.',
  },
  {
    id: 'canopy',
    src: '/images/album/nyungwe-canopy.jpg',
    title: 'Walk in the air',
    place: 'Nyungwe canopy',
    caption: 'The hanging bridge if you want the mist twice.',
  },
  {
    id: 'gorilla-family',
    src: '/images/album/gorilla-family.jpg',
    title: 'Susa family',
    place: 'Volcanoes National Park',
    caption: 'A mountain gorilla in the Karisimbi thicket. The permit is already in the fare.',
  },
  {
    id: 'kigali-centre',
    src: '/images/album/kigali-centre.jpg',
    title: 'Convention crown',
    place: 'Kigali',
    caption: 'The dome at dusk. The Hamwe desk sits a few hills over in Kiyovu.',
  },
]

export function getTour(slug: string): Tour | undefined {
  return tours.find((tour) => tour.slug === slug)
}

export function getActivity(slug: string): Activity | undefined {
  return activities.find((activity) => activity.slug === slug)
}

export function getTourById(id: string): Tour | undefined {
  return tours.find((tour) => tour.id === id)
}

export function getActivityById(id: string): Activity | undefined {
  return activities.find((activity) => activity.id === id)
}

export function getMembership(slug: string): MembershipPlan | undefined {
  return memberships.find((plan) => plan.slug === slug)
}

export function getMembershipById(id: string): MembershipPlan | undefined {
  return memberships.find((plan) => plan.id === id)
}

export function getCatalogName(kind: 'tour' | 'activity' | 'membership', id: string): string | undefined {
  if (kind === 'tour') return getTourById(id)?.name
  if (kind === 'activity') return getActivityById(id)?.name
  return getMembershipById(id)?.name
}

export function seatsLeft(tour: Tour): number {
  return Math.max(0, tour.seatsTotal - tour.seatsTaken)
}

export function circleForTour(tour: Tour): TravelerPreview[] {
  const count = Math.min(tour.seatsTaken, travelers.length)
  const host = travelers.find((person) => person.role === 'host')
  const guests = travelers.filter((person) => person.role === 'guest').slice(0, count - 1)
  return host ? [host, ...guests] : guests
}
